{
 "title": "Hypercore / Hyperswarm",
 "description": "All stats relevant for an application built on top of the hypercore stack, including hypercore, hyperswarm, hyperdht, udx",
 "tags": [
  "node.js",
  "nodejs",
  "hypercore",
  "hyperswarm",
  "hyperdht",
  "udx"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(nodejs_eventloop_lag_seconds, job)"
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(nodejs_version_info,service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(nodejs_eventloop_lag_seconds{service=\"$service\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "UP overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{service=\"$service\"})",
     "legendFormat": "Total UP"
    },
    {
     "expr": "up{service=\"$service\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "description": "The version of Node.js.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Package version",
   "type": "stat",
   "description": "The version in the package.json",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "package_version{service=\"$service\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Node.js Restarts",
   "type": "stat",
   "description": "The number of times Node.js restarted.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{service=\"$service\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Node.js"
    }
   ]
  },
  {
   "title": "Process runtime",
   "type": "stat",
   "description": "(days) hh:mm:ss since start",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{service=\"$service\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "UDX (networking)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total bytes transmitted/received (global UDX)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "udx_total_bytes_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "udx_total_bytes_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes/s transmitted/received (global UDX)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(udx_total_bytes_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Bytes received per second"
    },
    {
     "expr": "rate(udx_total_bytes_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Bytes transmitted per second"
    }
   ]
  },
  {
   "title": "Total packets transmitted/received (global UDX)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "udx_total_packets_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "udx_total_packets_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "packets/s transmitted/received (global UDX)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(udx_total_packets_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "packets transmitted / s"
    },
    {
     "expr": "rate(udx_total_packets_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "packets received / s"
    }
   ]
  },
  { "title": "Hypercore stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total cores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "hypercore_total_cores{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "hypercore_total_fully_downloaded_cores{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Total Peers Replicating Hypercores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "hypercore_total_peers{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Average RTT (round-trip time)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hypercore_round_trip_time_avg_seconds{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Inflight overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "hypercore_total_max_inflight_blocks{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "hypercore_total_inflight_blocks{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Global Cache Entries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "hypercore_global_cache_entries_total{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Hypercore Sessions",
   "type": "timeseries",
   "description": "Amount of hypercore sessions summed across all hypercores",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 22 },
   "targets": [
    {
     "expr": "hypercore_sessions_total{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Hypercore Sessions per Core",
   "type": "timeseries",
   "description": "Average amount of sessions per hypercore",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "hypercore_sessions_total{service=\"$service\", instance=\"$instance\"} /hypercore_total_cores",
     "legendFormat": "Average sessions per core"
    }
   ]
  },
  {
   "title": "Hotswaps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 22 },
   "targets": [
    {
     "expr": "hypercore_total_hotswaps{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Hotswaps per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 22 },
   "targets": [
    {
     "expr": "rate(hypercore_total_hotswaps{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Hotswaps / s"
    }
   ]
  },
  {
   "title": "Wire Messages Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hypercore_total_wire_sync_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_request_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_cancel_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_data_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_want_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_bitfield_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_range_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_extension_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_sync_received{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_request_received{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_cancel_received{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_data_received{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_want_received{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_bitfield_received{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_range_received{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_extension_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "Total received"
    }
   ]
  },
  {
   "title": "Wire Messages Received / Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(hypercore_total_wire_sync_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire sync RX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_request_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire request RX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_cancel_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire cancel RX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_data_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire data RX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_want_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire want RX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_bitfield_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire bitfield RX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_range_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire range RX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_extension_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire extension RX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_sync_received{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_request_received{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_cancel_received{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_data_received{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_want_received{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_bitfield_received{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_range_received{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_extension_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Total RX/s"
    }
   ]
  },
  {
   "title": "Wire Messages Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hypercore_total_wire_sync_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_request_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_cancel_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_data_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_want_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_bitfield_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_range_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_extension_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hypercore_total_wire_sync_transmitted{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_request_transmitted{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_cancel_transmitted{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_data_transmitted{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_want_transmitted{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_bitfield_transmitted{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_range_transmitted{service=\"$service\", instance=\"$instance\"} + hypercore_total_wire_extension_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "Total transmitted"
    }
   ]
  },
  {
   "title": "Wire Messages Transmitted / Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "rate(hypercore_total_wire_sync_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire Sync TX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_request_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire request TX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_cancel_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire cancel TX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_data_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire data TX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_want_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire want TX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_bitfield_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire bitfield TX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_range_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire range TX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_extension_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Wire extension TX/s"
    },
    {
     "expr": "rate(hypercore_total_wire_sync_transmitted{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_request_transmitted{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_cancel_transmitted{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_data_transmitted{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_want_transmitted{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_bitfield_transmitted{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_range_transmitted{service=\"$service\", instance=\"$instance\"}[$interval]) + rate(hypercore_total_wire_extension_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Total messages TX/s"
    }
   ]
  },
  {
   "title": "Swarm Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hyperswarm nr peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hyperswarm_nr_peers{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "Nr Peers"
    }
   ]
  },
  {
   "title": "Hyperswarm connections overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hyperswarm_client_connections_attempted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hyperswarm_client_connections_closed{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hyperswarm_client_connections_opened{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hyperswarm_server_connections_opened{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hyperswarm_server_connections_closed{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hyperswarm connections per second overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hyperswarm_client_connections_attempted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "client connections attempted / s"
    },
    {
     "expr": "rate(hyperswarm_client_connections_closed{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "client connections closed / s"
    },
    {
     "expr": "rate(hyperswarm_client_connections_opened{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "client connections opened / s"
    },
    {
     "expr": "rate(hyperswarm_server_connections_opened{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "server connections opened / s"
    },
    {
     "expr": "rate(hyperswarm_server_connections_closed{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "server connections closed / s"
    }
   ]
  },
  {
   "title": "Hyperswarm streams total packets transmitted/received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hyperswarm_total_packets_received_over_swarm_streams{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hyperswarm_total_packets_transmitted_over_swarm_streams{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hyperswarm streams packets/s transmitted/received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hyperswarm_total_packets_received_over_swarm_streams{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "packets/s received"
    },
    {
     "expr": "rate(hyperswarm_total_packets_transmitted_over_swarm_streams{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "packets/s transmitted"
    }
   ]
  },
  {
   "title": "Hyperswarm streams total bytes transmitted/received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hyperswarm_total_packets_received_over_swarm_streams{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hyperswarm_total_bytes_transmitted_over_swarm_streams{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hyperswarm streams bytes/s transmitted/received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(hyperswarm_total_bytes_received_over_swarm_streams{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "bytes/s received"
    },
    {
     "expr": "rate(hyperswarm_total_bytes_transmitted_over_swarm_streams{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "bytes/s transmitted"
    }
   ]
  },
  {
   "title": "Hyperswarm Total Retransmits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hyperswarm_total_retransmits_over_swarm_streams{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Hyperswarm Retransmits per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hyperswarm_total_retransmits_over_swarm_streams{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Retransmits/s"
    }
   ]
  },
  {
   "title": "Hyperswarm Total Fast-Recoveries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hyperswarm_total_fast_recoveries_over_swarm_streams{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Hyperswarm Fast-Recoveries per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hyperswarm_total_fast_recoveries_over_swarm_streams{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Fast-recoveries/s"
    }
   ]
  },
  {
   "title": "Hyperswarm Total Retransmission timeout Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hyperswarm_total_rto_count_over_swarm_streams{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Hyperswarm Retransmission-Timeouts per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hyperswarm_total_rto_count_over_swarm_streams{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "RTO/s"
    }
   ]
  },
  {
   "title": "MTU (average over all connections)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hyperswarm_avg_mtu{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Congestion Window (average over all connections)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hyperswarm_avg_congestion_window{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DHT Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "DHT sockets packets transmitted/received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dht_client_socket_packets_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_client_socket_packets_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_server_socket_packets_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_server_socket_packets_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT sockets packets/s transmitted/received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dht_client_socket_packets_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "client sockets rx/s"
    },
    {
     "expr": "rate(dht_client_socket_packets_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "client sockets tx/s"
    },
    {
     "expr": "rate(dht_server_socket_packets_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "server socket rx/s"
    },
    {
     "expr": "rate(dht_server_socket_packets_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "server socket tx/s"
    }
   ]
  },
  {
   "title": "DHT sockets bytes transmitted/received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dht_client_socket_bytes_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_client_socket_bytes_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_server_socket_bytes_received{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_server_socket_bytes_transmitted{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT sockets bytes/s transmitted/received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(dht_client_socket_bytes_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "client bytes rx/s"
    },
    {
     "expr": "rate(dht_client_socket_bytes_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "client bytes tx/s"
    },
    {
     "expr": "rate(dht_server_socket_bytes_received{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "server bytes rx/s"
    },
    {
     "expr": "rate(dht_server_socket_bytes_transmitted{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "server bytes tx/s"
    }
   ]
  },
  {
   "title": "Holepunching overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dht_consistent_punches{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_open_punches{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_random_punches{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT Queries Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dht_active_queries{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_total_queries{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dht_total_queries{service=\"$service\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Queries per second"
    }
   ]
  },
  {
   "title": "DHT Nodes Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dht_nr_nodes{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dht_nr_unique_node_ips{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT Records Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dht_nr_records{service=\"$service\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$interval]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$interval]) * 100",
     "legendFormat": "System CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$interval]) * 100",
     "legendFormat": "Total CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time Spent",
   "type": "timeseries",
   "description": "CPU time spent.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers and Requests",
   "type": "timeseries",
   "description": "Number of active handle and active requests.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "timeseries",
   "description": "Latency of the event loop.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Last - {{instance}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "P99 - {{instance}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "P50 - {{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Duration Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection duration.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{kind}} - {{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Duration of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{kind}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "Usage of heap memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Used - {{instance}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Resident - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "External - {{instance}}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} - {{kind}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "description": "Count of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{kind}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "timeseries",
   "description": "Usage of heap space.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{space}} - {{instance}}"
    }
   ]
  },
  {
   "title": "External memory used",
   "type": "timeseries",
   "description": "Usage of heap space.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{space}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heapsize used",
   "type": "timeseries",
   "description": "Usage of heap space.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  }
 ]
}